version: "3.8"
services:
  frontend:
    build:
      context: ./cmm-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./cmm-frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./cmm-backend
      dockerfile: Dockerfile
    volumes:
      - ./cmm-backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MONGODB_URI=mongodb://mongo:27017/${MONGO_DB}
    command: npm run dev
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cmm
      POSTGRES_PASSWORD: cmm1234
      POSTGRES_DB: cmm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

volumes:
  postgres_data:
